### Window ###

[window]
decorations = "None"
opacity = 0.5
startup_mode = "Windowed"

### Scrolling ###

[scrolling]
multiplier = 3

### Font ###

[font]
size = 10.0

[font.normal]
family = "Fira Code Nerd Font"
style = "Regular"

[font.bold]
family = "Fira Code Nerd Font"
style = "Bold"

[font.italic]
family = "Fira Code Nerd Font"
style = "Light Italic"

[font.glyph_offset]
x = 0
y = 0

[font.offset]
x = 0
y = 0

### Colors ###

[colors]
draw_bold_text_with_bright_colors = false

# Default colors
[colors.primary]
background = '0xffffff'
foreground = '0x1E1E1E'

# Colors the cursor will use if `custom_cursor_colors` is true
[colors.cursor]
text = '0xf1efee'
cursor = '0x68615e'

# Normal colors
[colors.normal]
black = '0xf1efee'
red = '0xf22c40'
green = '0x7b9726'
yellow = '0xc38418'
blue = '0x407ee7'
magenta = '0x6666ea'
cyan = '0x3d97b8'
white = '0x68615e'

# Bright colors
[colors.bright]
black = '0x9c9491'
red = '0xdf5320'
green = '0xe6e2e0'
yellow = '0xa8a19f'
blue = '0x766e6b'
magenta = '0x2c2421'
cyan = '0xc33ff3'
white = '0x1b1918'

### Bell ###
[bell]
animation = "EaseOutExpo"
color = "0xffffff"
duration = 0

### Cursor ###

[cursor]
style = "Underline"
unfocused_hollow = false
