### Window ###

[window]
decorations = "None"
opacity = 0.7
startup_mode = "Windowed"

### Scrolling ###

[scrolling]
multiplier = 3 

### Font ###

[font]
size = 11.0

[font.normal]
family = "Fira Code Nerd Font"
style = "Regular"

[font.bold]
family = "Fira Code Nerd Font"
style = "Bold"

[font.italic]
family = "Fira Code Nerd Font"
style = "Light Italic"

[font.glyph_offset]
x = 0
y = 0

[font.offset]
x = 0
y = 0

### Colors ###

[colors]
draw_bold_text_with_bright_colors = false

[colors.bright]
black = "0x969896"
blue = "0xb4b7b4"
cyan = "0xa3685a"
green = "0x282a2e"
magenta = "0xe0e0e0"
red = "0xde935f"
white = "0xffffff"
yellow = "0x373b41"

[colors.cursor]
cursor = "0xc5c8c6"
text = "0x1d1f21"

[colors.normal]
black = "0x1d1f21"
blue = "0x81a2be"
cyan = "0x8abeb7"
green = "0xb5bd68"
magenta = "0xb294bb"
red = "0xcc6666"
white = "0xc5c8c6"
yellow = "0xf0c674"

[colors.primary]
background = "0x2A2A2A"
foreground = "0xc5c8c6"

### Bell ###
[bell]
animation = "EaseOutExpo"
color = "0xffffff"
duration = 0

### Cursor ###

[cursor]
style = "Underline"
unfocused_hollow = false 
