format = """
[░▒▓](color_gray)\

$os\

[](bg:color_blue fg:color_gray)\

$directory\

[ ](fg:color_blue)\

\n$character"""

palette = 'tokyo-night'

[palettes.tokyo-night]
color_gray = '#a3aed2'
color_blue = '#769ff0'
color_white = '#e3e5e5'
color_black = '#090c0c'

[directory]
style = "fg:color_white bg:color_blue"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[os]
disabled = false
style = "bg:color_gray fg:color_black"

[os.symbols]
Windows = " 󰍲 "
Macos = " 󰀵 "
Arch = " 󰣇 "

[username]
show_always = true
style_user = "bg:color_gray fg:color_black"
style_root = "bg:color_gray fg:color_black"
format = '[ $user ]($style)'